version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/product"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      gradle-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/product/interfaces/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      npm-development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      npm-production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
