import test from 'node:test';
import assert from 'node:assert/strict';

import { cleanClaudeAttribution } from './clean-claude-attribution.mjs';

const FOOTER = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const DESCRIPTION_BLOCK = '\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)' +
  '\n\nhttps://claude.ai/code/session_abc\n\n---' +
  '\n_Generated by [Claude Code](https://claude.ai/code/session_abc)_';

test('removes only a Claude Code conversation footer', () => {
  assert.equal(cleanClaudeAttribution(`Authored update.${FOOTER}`), 'Authored update.');
});

test('removes the complete Claude Code PR-description block', () => {
  assert.equal(cleanClaudeAttribution(`## Summary\n\nAuthored update.${DESCRIPTION_BLOCK}`), '## Summary\n\nAuthored update.');
});

test('does not alter a mention that is not an attribution suffix', () => {
  const body = 'The branch is named claude/example, which is unrelated to this message.';
  assert.equal(cleanClaudeAttribution(body), body);
});

test('does not alter a footer with a non-Claude attribution', () => {
  const body = '\n\n---\n_Generated by [Someone Else](https://example.test)_';
  assert.equal(cleanClaudeAttribution(body), body);
});
