import test from 'node:test';
import assert from 'node:assert/strict';

import { cleanBotAttribution, cleanPullRequest } from './github-attribution-hygiene.mjs';

const FOOTER = '\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_';
const DESCRIPTION_BLOCK = '\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)' +
  '\n\nhttps://claude.ai/code/session_abc\n\n---' +
  '\n_Generated by [Claude Code](https://claude.ai/code/session_abc)_';

const REPO = 'alaiba/arcogine';
const FOOTER_BODY = `Authored update.${FOOTER}`;

function response(data, link = '') {
  return {
    ok: true,
    status: 200,
    headers: { get: (name) => (name.toLowerCase() === 'link' ? link : null) },
    json: async () => data,
  };
}

function githubFixture() {
  const calls = [];
  const fetchImpl = async (url, options = {}) => {
    calls.push({ url, options });
    const path = new URL(url).pathname;
    if (path === '/user') return response({ login: 'owner' });
    if (path === `/repos/${REPO}/pulls/42`) {
      if (options.method !== 'GET') return response({ body: JSON.parse(options.body).body });
      return response({ body: FOOTER_BODY, user: { login: 'owner' } });
    }
    if (path === `/repos/${REPO}/issues/42/comments`) {
      return response([
        { id: 1, body: FOOTER_BODY, user: { login: 'owner' } },
        { id: 2, body: FOOTER_BODY, user: { login: 'other-user' } },
      ]);
    }
    if (path === `/repos/${REPO}/pulls/42/reviews`) {
      return response([{ id: 3, body: FOOTER_BODY, user: { login: 'owner' } }]);
    }
    if (path === `/repos/${REPO}/pulls/42/comments`) {
      return response([{ id: 4, body: FOOTER_BODY, user: { login: 'owner' } }]);
    }
    if (path === `/repos/${REPO}/issues/comments/1` ||
      path === `/repos/${REPO}/pulls/42/reviews/3` ||
      path === `/repos/${REPO}/pulls/comments/4`) {
      return response({ body: JSON.parse(options.body).body });
    }
    throw new Error(`unexpected ${options.method ?? 'GET'} ${url}`);
  };
  return { calls, fetchImpl };
}

test('removes a generated footer from any bot', () => {
  assert.equal(cleanBotAttribution(`Authored update.${FOOTER}`), 'Authored update.');
  assert.equal(
    cleanBotAttribution('Authored update.\n\n---\n_Generated by [Other Bot](https://bot.example)_'),
    'Authored update.',
  );
});

test('removes the complete generated PR-description block', () => {
  assert.equal(cleanBotAttribution(`## Summary\n\nAuthored update.${DESCRIPTION_BLOCK}`), '## Summary\n\nAuthored update.');
});

test('removes a generated session block without a footer', () => {
  const body = 'Authored update.\n\n🤖 Generated with [Other Bot](https://bot.example)\n\nhttps://bot.example/session_abc';
  assert.equal(cleanBotAttribution(body), 'Authored update.');
});

test('does not alter a mention that is not an attribution suffix', () => {
  const body = 'The branch is named claude/example, which is unrelated to this message.';
  assert.equal(cleanBotAttribution(body), body);
});

test('does not alter ordinary prose that mentions generation', () => {
  const body = 'The report was generated by Someone Else for the release notes.';
  assert.equal(cleanBotAttribution(body), body);
});

test('dry-run never mutates and only reports authenticated-owner messages', async () => {
  const fixture = githubFixture();
  const logs = [];
  const result = await cleanPullRequest({
    number: 42,
    repo: REPO,
    fetchImpl: fixture.fetchImpl,
    token: 'test-token',
    log: (line) => logs.push(line),
  });

  assert.equal(result.changed, 4);
  assert.equal(fixture.calls.filter(({ options }) => options.method && options.method !== 'GET').length, 0);
  assert.equal(logs.filter((line) => /^Would clean (description|comment|review|inline comment) /.test(line)).length, 4);
});

test('apply mutates each eligible message kind and skips foreign authors', async () => {
  const fixture = githubFixture();
  const result = await cleanPullRequest({
    number: 42,
    repo: REPO,
    apply: true,
    fetchImpl: fixture.fetchImpl,
    token: 'test-token',
    log: () => {},
  });

  const mutations = fixture.calls.filter(({ options }) => options.method && options.method !== 'GET');
  assert.equal(result.changed, 4);
  assert.deepEqual(mutations.map(({ url, options }) => [options.method, new URL(url).pathname]), [
    ['PATCH', `/repos/${REPO}/pulls/42`],
    ['PATCH', `/repos/${REPO}/issues/comments/1`],
    ['PUT', `/repos/${REPO}/pulls/42/reviews/3`],
    ['PATCH', `/repos/${REPO}/pulls/comments/4`],
  ]);
  assert.equal(mutations.some(({ url }) => url.endsWith('/issues/comments/2')), false);
  assert.ok(mutations.every(({ options }) => JSON.parse(options.body).body === 'Authored update.'));
});
